--- 
output_dir: output
data_sources: 
- type: filesystem_unified
  items_root: /
  layouts_root: /

# Custom settings

# Use rsync + ssh for live site. To deploy:
#
#   % rake deploy:rsync
deploy:
  default:
    dst: "matt@iflowfor8hours.info:/var/www/iflowfor8hours.info"
    options: ['-ave ssh', '--exclude=.DS_Store', '--progress', '--exclude=*~']

# domain to which this site is deployed
base_url: http://www.iflowfor8hours.info

google_analytics:
  domain: iflowfor8hours.info
  site_id: UA-22586140-1

# currently used by logo
site_name: iflowfor8hours

# number of full featured posts to display on front
featured_count: 0

# number of excerpted posts to display on front
excerpt_count: 5

# number of other articles to reference at bottom of each article
other_articles_max: 3

# DISQUS Site Shortname. Comment out to disable.
disqus_shortname: iflowfor8hours
